### ISSUE TITLE
Full finetuning v.s. LoRA finetuning

### ISSUE THREAD

**Issue by joeyy5588** [zjysteven/lmms-finetune#17] opened 2024-08-07 23:26 UTC
Hi,

Thanks for the amazing repo!
I'm trying to figure out how to perform full finetuning like the script in the original LLaVA repo: [link](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune.sh), and lora finetuning: [link](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh).

In your [example_image.sh](https://github.com/zjysteven/lmms-finetune/blob/main/example_scripts/example_image.sh), should I first set TRAIN_VISION_PROJECTOR=True for both cases, and USE_LORA=False for full finetuning, and USE_LORA=True for LoRA finetuning?

Also is your LORA_R and LORA_ALPHA identical to those in the above links? (cuz I saw your default values are 8 while in the original llava repo they are set to 128 and 256).

Thank you!

**Comment by zjysteven** [comment] 2024-08-07 23:38
Hello, for a full finetuning the arguments would be like this
```bash
TRAIN_VISION_ENCODER=True                               # whether train the vision encoder
USE_VISION_LORA=False                                   # whether use lora for vision encoder (only effective when `TRAIN_VISION_ENCODER` is True)
TRAIN_VISION_PROJECTOR=True                             # whether train the vision projector (only full finetuning is supported)

USE_LORA=False                                          # whether use lora for llm
Q_LORA=False                                            # whether use q-lora for llm; only effective when `USE_LORA` is True
```
Specifically, `USE_LORA` is dedicated to the LLM part. And we assume that the LLM will always be finetuned (either full or lora or q-lora), so having `USE_LORA=False` means that the LLM will be fully finetuned.

Yes `LORA_R` and `LORA_ALPHA` share the same meaning to those in the other examples. I set them to 8 just for a quick experiment, not really indicating that they are recommended hyperparameters.

**Comment by joeyy5588** [comment] 2024-08-07 23:41
Thank you so much for the prompt reply! Closing the issue.

**Comment by joeyy5588** [comment] 2024-08-07 23:47
Sorry just came across another question: 
From this lora finetuning script: [link](https://github.com/haotian-liu/LLaVA/blob/main/scripts/v1_5/finetune_lora.sh) we can see that the `mm_projector_lr` is set to `2e-5`.
Is your `VISION_PROJECTOR` here equivalent to the `mm_projector` of the original repo?
If so, should we set `TRAIN_VISION_PROJECTOR=True` even if we are performing lora finetuning?

**Comment by zjysteven** [comment] 2024-08-07 23:56
Yes for LLaVA `VISION_PROJECTOR` is the `mm_projector`. One minor thing is that we don't support different learning rate as the official llava script does (as you linked, they use 2e-5 for `mm_projector` while 2e-4 for llm; yet whether this is optimal is unclear as there are issues in the llava repo reporting that using 2e-4 for llm is too large and people got reasonable loss curves when using 2e-5 as well).

Whether training the vision projector depends on your specific case. For example, I would definitely consider finetuning the projector if I finetune the vision encoder which comes before the projector in the forward pass. On the contrary if I keep the vision encoder fixed, then finetuning the projector may not be necessary.

**Comment by joeyy5588** [comment] 2024-08-08 03:16
Thanks for the clarification.
However, I found that every time I set `TRAIN_VISION_PROJECTOR=True`, I encountered this issue:
![image](https://github.com/user-attachments/assets/391173ab-86a9-4449-9af2-9f556d30d8d4)
I can confirm that after setting `TRAIN_VISION_PROJECTOR=False`, it works like charm.
Right now I'm setting`TRAIN_VISION_PROJECTOR=True` and `USE_LORA=True`
p.s. I don't have enough GPU RAM to test with the full-finetuning version (i.e. setting `USE_LORA=False`) to see if it works.

**Comment by zjysteven** [comment] 2024-08-08 03:20
Did you follow the installation steps in README and which version of deepspeed are you using? I'm asking because it seems you are using an environment specified by LLaVA, which uses an older version of deepspeed and might cause the error you are posting here. When I tested different combinations of arguments (`TRAIN_VISION_PROJECTOR`, `USE_LORA` etc) I never ran into this bug.

**Comment by joeyy5588** [comment] 2024-08-08 03:29
Hi @zjysteven,

I'm using the latest version of transformer and deepspeed
`transformer==4.44.0`, `deepspeed==0.14.4`
I simply change `TRAIN_VISION_PROJECTOR=False` to `TRAIN_VISION_PROJECTOR=True` in `example_scripts/example_image.sh` and execute it.

**Comment by zjysteven** [comment] 2024-08-08 04:13
@joeyy5588 OK I'm launching a training run now. Do you remember at how many steps you saw the error?

**Comment by zjysteven** [comment] 2024-08-08 04:23
The training run successfully finished on my end. Pasting the command for double check. My transformer and deepspeed version is the same as yours.
```bash
NUM_GPUS=1
DISTRIBUTED_ARGS="
    --nnodes=1 \
    --nproc_per_node ${NUM_GPUS} \
    --rdzv_backend c10d \
    --rdzv_endpoint localhost:0
"

# arguments that are very likely to be changed
# according to your own case
MODEL_ID=llava-1.5-7b                                   # model id; pick on by running `python supported_models.py`
TRAIN_DATA_PATH=./example_data/celeba_image_train.json  # path to the training data json file
EVAL_DATA_PATH=./example_data/celeba_image_eval.json    # path to the evaluation data json file (optional)
IMAGE_FOLDER=./example_data/images                      # path to the image root folder; if provided, the image paths in the json should be relative
VIDEO_FOLDER=./example_data/videos                      # path to the video root folder; if provided, the video paths in the json should be relative
NUM_FRAMES=8                                            # how many frames are sampled from each video

TRAIN_VISION_ENCODER=False                              # whether train the vision encoder
USE_VISION_LORA=False                                   # whether use lora for vision encoder (only effective when `TRAIN_VISION_ENCODER` is True)
TRAIN_VISION_PROJECTOR=True                            # whether train the vision projector (only full finetuning is supported)

USE_LORA=True                                           # whether use lora for llm
Q_LORA=False                                            # whether use q-lora for llm; only effective when `USE_LORA` is True
LORA_R=8                                                # the lora rank (both llm and vision encoder)
LORA_ALPHA=8                                            # the lora alpha (both llm and vision encoder)

RUN_ID=${MODEL_ID}_lora-${USE_LORA}_qlora-${Q_LORA}     # a custom run id that determines the checkpoint folder and wandb run name

DS_STAGE=zero3                                          # deepspeed stage; < zero2 | zero3 >
PER_DEVICE_BATCH_SIZE=2                                 # batch size per GPU
GRAD_ACCUM=1                                            # gradient accumulation steps
NUM_EPOCHS=5                                            # number of training epochs

LR=2e-5                                                 # learning rate
MODEL_MAX_LEN=512                                       # maximum input length of the model


torchrun $DISTRIBUTED_ARGS train.py \
    --model_id $MODEL_ID \
    --data_path $TRAIN_DATA_PATH \
    --eval_data_path $EVAL_DATA_PATH \
    --image_folder $IMAGE_FOLDER \
    --video_folder $VIDEO_FOLDER \
    --num_frames $NUM_FRAMES \
    --output_dir ./checkpoints/$RUN_ID \
    --report_to wandb \
    --run_name $RUN_ID \
    --deepspeed ./ds_configs/${DS_STAGE}.json \
    --bf16 True \
    --num_train_epochs $NUM_EPOCHS \
    --per_device_train_batch_size $PER_DEVICE_BATCH_SIZE \
    --per_device_eval_batch_size $PER_DEVICE_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --eval_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate ${LR} \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length $MODEL_MAX_LEN \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --train_vision_encoder $TRAIN_VISION_ENCODER \
    --use_vision_lora $USE_VISION_LORA \
    --train_vision_projector $TRAIN_VISION_PROJECTOR \
    --use_lora $USE_LORA \
    --q_lora $Q_LORA \
    --lora_r $LORA_R \
    --lora_alpha $LORA_ALPHA
```

**Comment by zjysteven** [comment] 2024-08-17 15:28
@joeyy5588 Closing now. Feel free to reopen if there are any other questions.

**Closed by zjysteven** 2024-08-17 15:28 UTC

**Comment by cui0711** [comment] 2025-04-15 03:38
Hi, when I set TRAIN_VISION_PROJECTOR=True, I encounter the following error during training: **RuntimeError: only Tensors of floating point dtype can require gradients.**
However, when I set TRAIN_VISION_PROJECTOR=False, the model trains normally without any issues.
I am using the following training script:
```bash
#!/bin/bash
set -euo pipefail

export NCCL_DEBUG=INFO
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
export NCCL_SHM_DISABLE=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True


NUM_GPUS=4
DISTRIBUTED_ARGS="
    --nnodes=1 \
    --nproc_per_node ${NUM_GPUS} \
    --rdzv_backend c10d \
    --rdzv_endpoint localhost:0
"

MODEL_ID=qwen2.5-vl-7b-instruct                                   # model id; pick on by running `python supported_models.py`
TRAIN_DATA_PATH=/guji/dataset/mydataset/mydataset_style_train.json   # path to the training data json file
MODEL_LOCAL_PATH=/guji/weights/Qwen2.5-VL-7B-Instruct
IMAGE_FOLDER=/guji/dataset/mydataset/

TRAIN_VISION_ENCODER=True                              # whether train the vision encoder
USE_VISION_LORA=True                                   # whether use lora for vision encoder (only effective when `TRAIN_VISION_ENCODER` is True)
TRAIN_VISION_PROJECTOR=True                            # whether train the vision projector (only full finetuning is supported)

USE_LORA=True                                           # whether use lora for llm
Q_LORA=True                                            # whether use q-lora for llm; only effective when `USE_LORA` is True
LORA_R=64                                                # the lora rank (both llm and vision encoder)
LORA_ALPHA=128                                            # the lora alpha (both llm and vision encoder)
LORA_DROPOUT=0.1

RUN_ID=${MODEL_ID}_lora-${USE_LORA}_qlora-${Q_LORA}_mydataset_style_train     # a custom run id that determines the checkpoint folder and wandb run name

DS_STAGE=zero2                                          # deepspeed stage; < zero2 | zero3 >
PER_DEVICE_BATCH_SIZE=2                                 # batch size per GPU
GRAD_ACCUM=2                                            # gradient accumulation steps
NUM_EPOCHS=3                                            # number of training epochs
MAX_GRAD_NORM=8.0
LR=2e-5                                                 # learning rate
MODEL_MAX_LEN=16384                                       # maximum input length of the model


torchrun $DISTRIBUTED_ARGS train.py \
    --model_id $MODEL_ID \
    --model_local_path $MODEL_LOCAL_PATH \
    --data_path $TRAIN_DATA_PATH \
    --image_folder $IMAGE_FOLDER \
    --output_dir ./checkpoints/$RUN_ID \
    --report_to wandb \
    --run_name $RUN_ID \
    --deepspeed ./ds_configs/${DS_STAGE}.json \
    --bf16 True \
    --num_train_epochs $NUM_EPOCHS \
    --per_device_train_batch_size $PER_DEVICE_BATCH_SIZE \
    --per_device_eval_batch_size $PER_DEVICE_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --max_grad_norm $MAX_GRAD_NORM \
    --eval_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 2 \
    --learning_rate ${LR} \
    --weight_decay 0.01 \
    --warmup_ratio 0.1 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length $MODEL_MAX_LEN \
    --gradient_checkpointing True \
    --dataloader_num_workers 16 \
    --train_vision_encoder $TRAIN_VISION_ENCODER \
    --use_vision_lora $USE_VISION_LORA \
    --train_vision_projector $TRAIN_VISION_PROJECTOR \
    --use_lora $USE_LORA \
    --q_lora $Q_LORA \
    --lora_r $LORA_R \
    --lora_alpha $LORA_ALPHA \
    --lora_dropout $LORA_DROPOUT
```

**Comment by lavinal712** [comment] 2025-04-15 07:31
@cui0711 Thank you for submitting this issue. Please create a separate issue so it can be tracked. I will respond when I am available.

**Comment by lavinal712** [comment] 2025-04-16 01:55
@cui0711 https://github.com/huggingface/peft/issues/1720 This explains the cause of the problem and the proposed solution.

In your case, 

```python
# train.py

# llm quantization config (for q-lora)
    bnb_config = None
    if lora_args.use_lora and lora_args.q_lora:
        from transformers import BitsAndBytesConfig
        rank0_print("Quantization for LLM enabled...")
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=compute_dtype,
            bnb_4bit_quant_type="nf4", 
            llm_int8_skip_modules=["visual.merger", "visual.patch_embed"]
        )
```

**Comment by cui0711** [comment] 2025-04-16 03:02
@lavinal712 Thanks for your response and assistance! 
The error I raised yesterday occurred when I set both TRAIN_VISION_PROJECTOR=True and Q_LORA=True. But when I only set TRAIN_VISION_PROJECTOR=True and Q_LORA=False, the error no longer occurred.

**Comment by lavinal712** [comment] 2025-04-16 03:11
> [@lavinal712](https://github.com/lavinal712) Thanks for your response and assistance! The error I raised yesterday occurred when I set both TRAIN_VISION_PROJECTOR=True and Q_LORA=True. But when I only set TRAIN_VISION_PROJECTOR=True and Q_LORA=False, the error no longer occurred.

Yes, it is caused by bitsandbytes in `peft`.
