### ISSUE TITLE
Loss and grad.norm are 0?

### ISSUE THREAD

**Issue by Nicerice96** [zjysteven/lmms-finetune#55] opened 2024-11-23 22:26 UTC
Hello! I was wondering if I could get some insight into the issue I'm having right now? I pass in a video data set in the structure:

Videos
-CPR
--CPRvideos.mp4
-PPV
--PPVvideos.mp4
-ETT
--CPRvideos.mp4
...

and I pass in the JSON (eval and train) in this format

```JSON
[
    {
        "video": "CPR/CPR5(1)(1).mp4",
        "conversations": [
            {
                "from": "human",
                "value": "<video>Please provide a detailed description of the video."
            },
            {
                "from": "gpt",
                "value": "This video shows a healthcare provider performing chest compressions on a newborn baby. The compressions are being delivered at the appropriate depth and rate for neonatal resuscitation."
            }
        ]
    },
    
    ... rest of the videos 
    
    ]

```
    
    
Your script is fantastic and has gotten us far, however I am wondering what potentially causing loss and gradnorm being 0 through each epoch?

This is the example.sh
```bash
NUM_GPUS=1
DISTRIBUTED_ARGS="--nnodes=1 --nproc_per_node ${NUM_GPUS} --rdzv_backend c10d --rdzv_endpoint localhost:0"
MODEL_ID=llava-next-video-7b
TRAIN_DATA_PATH=/content/train.json
EVAL_DATA_PATH=/content/eval.json
IMAGE_FOLDER=./example_data/images
VIDEO_FOLDER=/content/drive/MyDrive/Capstone/Videos1
NUM_FRAMES=8
TRAIN_VISION_ENCODER=False
USE_VISION_LORA=True
TRAIN_VISION_PROJECTOR=False
USE_LORA=True
Q_LORA=False
LORA_R=8
LORA_ALPHA=8
RUN_ID=${MODEL_ID}_lora-${USE_LORA}_qlora-${Q_LORA}
DS_STAGE=zero2
PER_DEVICE_BATCH_SIZE=1
GRAD_ACCUM=2
NUM_EPOCHS=5
LR=2e-5
MODEL_MAX_LEN=512

# Run training command
torchrun $DISTRIBUTED_ARGS train.py \
 --model_id $MODEL_ID \
 --data_path $TRAIN_DATA_PATH \
 --eval_data_path $EVAL_DATA_PATH \
 --image_folder $IMAGE_FOLDER \
 --video_folder $VIDEO_FOLDER \
 --num_frames $NUM_FRAMES \
 --output_dir ./checkpoints/$RUN_ID \
 --report_to wandb \
 --run_name $RUN_ID \
 --deepspeed ./ds_configs/${DS_STAGE}.json \
 --bf16 True \
 --num_train_epochs $NUM_EPOCHS \
 --per_device_train_batch_size $PER_DEVICE_BATCH_SIZE \
 --per_device_eval_batch_size $PER_DEVICE_BATCH_SIZE \
 --gradient_accumulation_steps $GRAD_ACCUM \
 --eval_strategy "epoch" \
 --save_strategy "epoch" \
 --save_total_limit 1 \
 --learning_rate ${LR} \
 --weight_decay 0. \
 --warmup_ratio 0.03 \
 --lr_scheduler_type "cosine" \
 --logging_steps 1 \
 --tf32 True \
 --model_max_length $MODEL_MAX_LEN \
 --gradient_checkpointing True \
 --dataloader_num_workers 2 \
 --train_vision_encoder $TRAIN_VISION_ENCODER \
 --use_vision_lora $USE_VISION_LORA \
 --train_vision_projector $TRAIN_VISION_PROJECTOR \
 --use_lora $USE_LORA \
 --q_lora $Q_LORA \
 --lora_r $LORA_R \
 --lora_alpha $LORA_ALPHA
 ```
 
 Thanks zjysteven!

**Comment by Nicerice96** [comment] 2024-11-23 23:16
Right okay, thank you so much I'll get back to you!

**Comment by Nicerice96** [comment] 2024-11-23 23:43
Hi, zjysteven


After running your colab script, it appears I'm getting 0 loss and 0 grad_norm


<img width="1415" alt="image" src="https://github.com/user-attachments/assets/c10dad95-c081-49e7-a8aa-ee9b6e37d45a">



```

	base_model.model.language_model.model.layers.31.mlp.gate_proj.lora_A.default.weight
	base_model.model.language_model.model.layers.31.mlp.gate_proj.lora_B.default.weight
	base_model.model.language_model.model.layers.31.mlp.up_proj.lora_A.default.weight
	base_model.model.language_model.model.layers.31.mlp.up_proj.lora_B.default.weight
	base_model.model.language_model.model.layers.31.mlp.down_proj.lora_A.default.weight
	base_model.model.language_model.model.layers.31.mlp.down_proj.lora_B.default.weight
Loading data...
Parameter Offload: Total persistent parameters: 12137472 in 665 params
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose "Don't visualize my results"
wandb: Tracking run with wandb version 0.18.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
  0% 0/175 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (530 > 512). Running this sequence through the model will result in indexing errors
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
Token indices sequence length is longer than the specified maximum sequence length for this model (584 > 512). Running this sequence through the model will result in indexing errors
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)
Token indices sequence length is longer than the specified maximum sequence length for this model (542 > 512). Running this sequence through the model will result in indexing errors
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 3.3333333333333333e-06, 'epoch': 0.03}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 6.666666666666667e-06, 'epoch': 0.06}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1e-05, 'epoch': 0.09}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1.3333333333333333e-05, 'epoch': 0.11}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1.6666666666666667e-05, 'epoch': 0.14}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 2e-05, 'epoch': 0.17}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1.9998272238333606e-05, 'epoch': 0.2}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1.99930895503665e-05, 'epoch': 0.23}
{'loss': 0.0, 'grad_norm': 0.0, 'learning_rate': 1.99844537269886e-05, 'epoch': 0.26}
  5% 9/175 [00:56<09:44,  3.52s/it]W1123 23:41:16.124000 7112 torch/distributed/elastic/agent/server/api.py:704] Received Signals.SIGINT death signal, shutting down workers
W1123 23:41:16.125000 7112 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 7138 closing signal SIGINT
Traceback (most recent call last):

```



Sorry for the inconvenience but we've been trying for ages any assitance would be massively appreciated!

Thanks!!

**Comment by zjysteven** [comment] 2024-11-23 23:47
Can you also run the unmodified example_video.sh? The colab hasn't been updated for a while.
________________________________

**Comment by Nicerice96** [comment] 2024-11-23 23:49
I believe I did? I ran ir directly from this github: here I'll copy paste it here


```bash
NUM_GPUS=1
DISTRIBUTED_ARGS="
    --nnodes=1 \
    --nproc_per_node ${NUM_GPUS} \
    --rdzv_backend c10d \
    --rdzv_endpoint localhost:0
"

# arguments that are very likely to be changed
# according to your own case
MODEL_ID=llava-next-video-7b                            # model id; pick on by running `python supported_models.py`
TRAIN_DATA_PATH=./example_data/ego4d_video_train.json   # path to the training data json file
EVAL_DATA_PATH=./example_data/ego4d_video_eval.json     # path to the evaluation data json file (optional)
IMAGE_FOLDER=./example_data/images                      # path to the image root folder; if provided, the image paths in the json should be relative
VIDEO_FOLDER=./example_data/videos                      # path to the video root folder; if provided, the video paths in the json should be relative
NUM_FRAMES=8                                            # how many frames are sampled from each video

TRAIN_VISION_ENCODER=False                              # whether train the vision encoder
USE_VISION_LORA=False                                   # whether use lora for vision encoder (only effective when `TRAIN_VISION_ENCODER` is True)
TRAIN_VISION_PROJECTOR=False                            # whether train the vision projector (only full finetuning is supported)

USE_LORA=True                                           # whether use lora for llm
Q_LORA=False                                            # whether use q-lora for llm; only effective when `USE_LORA` is True
LORA_R=8                                                # the lora rank (both llm and vision encoder)
LORA_ALPHA=8                                            # the lora alpha (both llm and vision encoder)

RUN_ID=${MODEL_ID}_lora-${USE_LORA}_qlora-${Q_LORA}     # a custom run id that determines the checkpoint folder and wandb run name

DS_STAGE=zero3                                          # deepspeed stage; < zero2 | zero3 >
PER_DEVICE_BATCH_SIZE=2                                 # batch size per GPU
GRAD_ACCUM=1                                            # gradient accumulation steps
NUM_EPOCHS=5                                            # number of training epochs

LR=2e-5                                                 # learning rate
MODEL_MAX_LEN=512                                       # maximum input length of the model


torchrun $DISTRIBUTED_ARGS train.py \
    --model_id $MODEL_ID \
    --data_path $TRAIN_DATA_PATH \
    --eval_data_path $EVAL_DATA_PATH \
    --image_folder $IMAGE_FOLDER \
    --video_folder $VIDEO_FOLDER \
    --num_frames $NUM_FRAMES \
    --output_dir ./checkpoints/$RUN_ID \
    --report_to wandb \
    --run_name $RUN_ID \
    --deepspeed ./ds_configs/${DS_STAGE}.json \
    --bf16 True \
    --num_train_epochs $NUM_EPOCHS \
    --per_device_train_batch_size $PER_DEVICE_BATCH_SIZE \
    --per_device_eval_batch_size $PER_DEVICE_BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --eval_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 1 \
    --learning_rate ${LR} \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length $MODEL_MAX_LEN \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --train_vision_encoder $TRAIN_VISION_ENCODER \
    --use_vision_lora $USE_VISION_LORA \
    --train_vision_projector $TRAIN_VISION_PROJECTOR \
    --use_lora $USE_LORA \
    --q_lora $Q_LORA \
    --lora_r $LORA_R \
    --lora_alpha $LORA_ALPHA
    ```

**Comment by zjysteven** [comment] 2024-11-23 23:55
Ok I will try to see if I can reproduce asap

**Comment by Nicerice96** [comment] 2024-11-23 23:57
I am thoroughly impressed at how willing you are to help, thank you so much!!

**Comment by zjysteven** [comment] 2024-11-24 06:10
Hi @Nicerice96 thank you for reporting this. I can reproduce it and I've found the fix and cause. Just set a large enough `MODEL_MAX_LEN`, say 4096, and then you will see loss being not 0. If you are curious about what happened, you can continue to read.

So basically it's related to an earlier update in the transformers library that I described in https://github.com/zjysteven/lmms-finetune/issues/43#issue-2593395378. The huggingface maintainers added a related config for llava-next-video 4 days ago, which triggered the new processing behavior of expanding the <video> token at preprocessing stage rather than within the LLM's forward pass as before. As a result, having a small `MODEL_MAX_LEN` will actually include none of your input texts because there are already a lot of <video> tokens there that reach `MODEL_MAX_LEN`. Having a large enough `MODEL_MAX_LEN` thus can solve the problem.

Again, the script for inspecting the output of the collator that I shared here https://github.com/zjysteven/lmms-finetune/issues/55#issuecomment-2495675125 could be very helpful, which is exactly how I identify the cause of this bug.

**Comment by Nicerice96** [comment] 2024-11-24 16:26
Hey zjysteven,


OHHHHH, yeah I did notice that on their repo, the tokenizer.config was updated. Thought nothing of it, but that makes a lot more sense, now that you've described it. Okay, thank you so much!!

Thanks,

**Comment by zjysteven** [comment] 2024-11-24 16:29
No problem. Closing now.

**Closed by zjysteven** 2024-11-24 16:29 UTC
